"""Tests for the Phase 3.2 improvement-loop rewrite.

These tests exercise the real eval harness and prompt-evolution cases while
mocking the reflection LLM so they do not require a live Ollama/cloud key.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import shared.improvement_loop as improvement_loop
from shared.improvement_loop import run_improvement_cycle
from shared.prompt_evolution import default_eval_cases


def _mock_llm_good(prompt: str, eval_summary: dict) -> dict:
    return {
        "reflection": "Test reflection: prompt lacks tool instructions.",
        "root_causes": [
            {"area": "prompt", "detail": "missing explicit tool-use guidance"}
        ],
        "proposals": [
            {
                "type": "patch",
                "relative_path": "shared/improvement_loop_test_patch.py",
                "new_content": "# test patch content generated by improvement loop\n",
                "reason": "fix test issue",
            },
            {
                "type": "skill",
                "name": "Test improvement skill",
                "summary": "Captures a test pattern from the improvement loop.",
                "body": "When testing, always verify proposals are concrete and safe.",
                "tags": ["auto", "improvement-loop", "test"],
            },
            {
                "type": "prompt_variant",
                "prompt_text": "You are SHIMS. Think step by step and output valid JSON when using tools.",
                "reason": "Strengthen tool-use instructions.",
            },
        ],
    }


def _mock_llm_empty(prompt: str, eval_summary: dict) -> dict:
    return {}


def _mock_llm_invalid(prompt: str, eval_summary: dict) -> str:
    return "not a dict"


def test_uses_real_prompt_eval_cases(monkeypatch) -> None:
    """The prompt eval run should execute the real default_eval_cases()."""
    monkeypatch.setattr(improvement_loop, "_call_reflection_llm", _mock_llm_empty)

    result = run_improvement_cycle("You are SHIMS.")

    prompt_run = result["prompt"]
    assert prompt_run["ok"] is True
    assert prompt_run["summary"]["cases"] == len(default_eval_cases())
    assert result["reflection"]["prompt_score"] == prompt_run["summary"]["score"]


def test_run_with_llm_proposals(monkeypatch) -> None:
    """When the LLM returns concrete proposals, each type is materialized."""
    monkeypatch.setattr(improvement_loop, "_call_reflection_llm", _mock_llm_good)

    # Capture patch proposals without writing real evolution artifacts.
    captured_patch: dict = {}

    def fake_propose_patch(*, relative_path: str, new_content: str, reason: str, **kwargs) -> dict:
        captured_patch.update(
            {"relative_path": relative_path, "new_content": new_content, "reason": reason, **kwargs}
        )
        return {
            "ok": True,
            "proposal_id": "fake-patch-id",
            "type": "patch",
            "relative_path": relative_path,
        }

    monkeypatch.setattr(improvement_loop, "propose_patch", fake_propose_patch)

    result = run_improvement_cycle("You are SHIMS.")

    assert result["ok"] is True
    assert result["reflection"]["text"] == "Test reflection: prompt lacks tool instructions."
    assert result["reflection"]["root_causes"][0]["area"] == "prompt"

    types = {p["type"] for p in result["proposals"]}
    assert "skill" in types
    assert "prompt_variant" in types
    assert "patch" in types

    assert captured_patch["relative_path"] == "shared/improvement_loop_test_patch.py"
    assert "# test patch content" in captured_patch["new_content"]
    assert captured_patch.get("scope") == "improvement_loop"


def test_disallowed_patch_target_is_blocked(monkeypatch) -> None:
    """Immutable/disallowed targets must be rejected by the real propose_patch path."""
    monkeypatch.setattr(
        improvement_loop,
        "_call_reflection_llm",
        lambda _p, _s: {
            "proposals": [
                {
                    "type": "patch",
                    "relative_path": "shared/security.py",
                    "new_content": "# unsafe edit\n",
                    "reason": "should be blocked",
                }
            ]
        },
    )

    result = run_improvement_cycle("You are SHIMS.")

    patch_proposals = [p for p in result["proposals"] if p.get("type") == "patch"]
    assert len(patch_proposals) == 1
    assert patch_proposals[0]["ok"] is False
    assert patch_proposals[0].get("status") == "blocked"


def test_llm_failure_falls_back_to_heuristics(monkeypatch) -> None:
    """If the reflection LLM returns nothing, deterministic fallbacks run."""
    monkeypatch.setattr(improvement_loop, "_call_reflection_llm", _mock_llm_empty)
    monkeypatch.setattr(
        improvement_loop,
        "run_reliability_evals",
        lambda: {
            "ok": False,
            "results": [
                {"name": "fake_case", "ok": False, "message": "failed", "details": {}}
            ],
        },
    )
    monkeypatch.setattr(
        improvement_loop,
        "_run_wave_latency_evals",
        lambda: {"ok": False, "error": "subprocess failed"},
    )

    result = run_improvement_cycle("You are SHIMS.")

    assert result["ok"] is True
    types = {p["type"] for p in result["proposals"]}
    assert "skill" in types
    assert "prompt_variant" in types


def test_invalid_llm_response_uses_fallback(monkeypatch) -> None:
    """A non-dict LLM response must not crash the cycle."""
    monkeypatch.setattr(improvement_loop, "_call_reflection_llm", _mock_llm_invalid)
    monkeypatch.setattr(
        improvement_loop,
        "run_reliability_evals",
        lambda: {
            "ok": False,
            "results": [
                {"name": "fake_case", "ok": False, "message": "failed", "details": {}}
            ],
        },
    )

    result = run_improvement_cycle("You are SHIMS.")

    assert result["ok"] is True
    assert result["reflection"]["llm_error"] != ""
    assert any(p["type"] == "skill" for p in result["proposals"])


def test_list_improvement_runs(monkeypatch) -> None:
    """Runs are persisted and retrievable."""
    monkeypatch.setattr(improvement_loop, "_call_reflection_llm", _mock_llm_empty)

    result = run_improvement_cycle("You are SHIMS.")
    runs = improvement_loop.list_improvement_runs(limit=10)

    assert any(r["run_id"] == result["run_id"] for r in runs)


if __name__ == "__main__":
    import pytest

    pytest.main([__file__, "-v", "--tb=short"])
