"""
Edge bundle assembly + manifest.

A bundle is the deployable unit for one edge device: a directory containing
   <bundle>/
     model.npz          — ternary weights
     model.json         — model metadata
     manifest.json      — what this bundle is, what it expects, who approved it
     runner.py          — minimal Python entry point that loads model and serves
     README.md          — operator-facing notes

The pharma QA team reviews the manifest. Once signed off, copy the bundle to
the device and run `python runner.py` (or compile the C runner for Pentium-
class nodes). No internet required to operate.
"""
from __future__ import annotations
import hashlib
import json
import shutil
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path

from .profiles import EdgeProfile, get_profile
from .ternary import TernaryMLP, save_ternary


@dataclass
class EdgeManifest:
    bundle_id: str
    job: str                              # "hazard_micro" | "mass_check" | "thermal_runaway" | ...
    profile_id: str
    teacher_version: str                  # which version of the symbolic verifier
    student_meta: dict                    # accuracy, params, etc.
    safety_envelope: dict = field(default_factory=dict)
    built_at: float = field(default_factory=time.time)
    approved_by: str | None = None         # QA sign-off; None until reviewed
    sha256: str | None = None              # of model.npz


def build_edge_bundle(
    mlp: TernaryMLP,
    *,
    job: str,
    profile_id: str,
    output_dir: str | Path,
    teacher_version: str = "verifier@0.1.0",
    safety_envelope: dict | None = None,
) -> EdgeManifest:
    """Write a complete bundle to `output_dir`. Returns the manifest."""
    profile = get_profile(profile_id)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Save the model
    save_ternary(mlp, out / "model.npz")

    # Sanity: does it fit?
    size_kb = (out / "model.npz").stat().st_size // 1024
    if size_kb > profile.max_model_kb:
        raise ValueError(
            f"Model is {size_kb} KB — exceeds {profile.profile_id} max of {profile.max_model_kb} KB"
        )

    # Hash the model for tamper detection
    h = hashlib.sha256((out / "model.npz").read_bytes()).hexdigest()

    bundle_id = f"edge-{job}-{profile_id}-{h[:8]}"
    manifest = EdgeManifest(
        bundle_id=bundle_id,
        job=job,
        profile_id=profile_id,
        teacher_version=teacher_version,
        student_meta=dict(mlp.meta),
        safety_envelope=safety_envelope or _default_safety(job),
        sha256=h,
    )
    (out / "manifest.json").write_text(json.dumps(asdict(manifest), indent=2, default=str))

    # Drop the minimal runner
    runner_src = _RUNNER_TEMPLATE.format(job=job)
    (out / "runner.py").write_text(runner_src)
    (out / "README.md").write_text(_readme_for(job, profile, size_kb, manifest))

    return manifest


def _default_safety(job: str) -> dict:
    """Default safety envelope per job. The micro-net must NEVER auto-act
    outside this envelope; it can only advise/alert."""
    if job == "hazard_micro":
        return {"action_class": "advise_only", "human_in_loop": True,
                "fallback": "phone_supervisor"}
    if job == "mass_check":
        return {"action_class": "block_next_step",
                "max_consecutive_blocks": 2,
                "human_override": "supervisor_pin"}
    if job == "thermal_runaway":
        return {"action_class": "alarm + throttle_pump_to_zero",
                "auto_throttle_threshold": "pre_runaway",
                "auto_shutdown_threshold": "runaway",
                "human_override": "lab_head"}
    return {"action_class": "advise_only"}


def _readme_for(job: str, profile: EdgeProfile, size_kb: int, m: EdgeManifest) -> str:
    return (
        f"# Shims Edge bundle: {m.bundle_id}\n\n"
        f"Job: **{job}**\n"
        f"Device profile: **{profile.profile_id}** ({profile.cpu}, {profile.ram_mb} MB RAM)\n"
        f"Model size: {size_kb} KB (limit {profile.max_model_kb} KB)\n"
        f"Latency budget: {profile.max_latency_ms} ms / inference\n\n"
        f"## Safety envelope\n"
        f"```\n{json.dumps(m.safety_envelope, indent=2)}\n```\n\n"
        f"## QA sign-off\n"
        f"Approved by: {m.approved_by or '(pending)'}\n\n"
        f"Once approved, scp this directory to the device and run `python3 runner.py`.\n"
    )


_RUNNER_TEMPLATE = '''"""Minimal edge runner for job {job!r}. Generated by Shims Chem."""
from __future__ import annotations
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent


def _load():
    from shims_chem.edge.ternary import load_ternary    # type: ignore
    return load_ternary(HERE / "model.npz")


def main():
    mlp = _load()
    line = sys.stdin.readline()
    if not line:
        sys.exit(0)
    arr = np.array(json.loads(line), dtype=np.float32)
    if arr.ndim == 1:
        arr = arr[None, :]
    probs = mlp.predict(arr)
    print(json.dumps({{"class": int(probs.argmax(axis=1)[0]),
                        "probs": probs[0].tolist()}}))


if __name__ == "__main__":
    main()
'''
