"""App Factory — reusable scaffold for SHIMS vertical apps.

This module gives SHIMS Omni (and its Coder / Swarm agents) deterministic
helpers to create, mount, and extend self-contained FastAPI apps under
``apps/<name>/``.  It is intentionally plain: no LLM calls, no risky
auto-wiring of live source files beyond the allowed app directory.

Typical usage from a tool or agent:

    from shared.app_factory import ensure_app_package, create_app_template_files
    ensure_app_package("todo_demo")
    create_app_template_files("todo_demo", prefix="/todo", title="Todo Demo")

Then the agent fills domain-specific services, routes, templates, and tests.
"""
from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from fastapi import APIRouter, FastAPI
from fastapi.staticfiles import StaticFiles

from .config import ROOT_DIR, settings
from .security import new_id

APPS_DIR = ROOT_DIR / "apps"
STORAGE_DIR = Path(settings.database_path).parent
TEMPLATES_DIR = ROOT_DIR / "frontend"


def derive_paths(app_name: str) -> dict[str, Path]:
    """Return the canonical paths for a new vertical app."""
    app_dir = APPS_DIR / app_name
    return {
        "app_dir": app_dir,
        "services_dir": app_dir / "services",
        "templates_dir": app_dir / "templates",
        "static_dir": app_dir / "static",
        "css_dir": app_dir / "static" / "css",
        "js_dir": app_dir / "static" / "js",
        "routers_dir": app_dir / "routers",
        "tests_dir": ROOT_DIR / "tests",
        "db_path": STORAGE_DIR / f"{app_name}.sqlite3",
    }


def ensure_app_package(app_name: str) -> dict[str, Path]:
    """Create the app folder skeleton (idempotent)."""
    paths = derive_paths(app_name)
    for d in ["services_dir", "templates_dir", "css_dir", "js_dir", "routers_dir"]:
        paths[d].mkdir(parents=True, exist_ok=True)
    # Make the package importable.
    for init in (paths["app_dir"] / "__init__.py", paths["routers_dir"] / "__init__.py", paths["services_dir"] / "__init__.py"):
        if not init.exists():
            init.write_text("# auto-generated by shared/app_factory.py\n", encoding="utf-8")
    return paths


def mount_app_static(app: FastAPI, app_name: str, prefix: str | None = None) -> None:
    """Mount an app's static directory at ``/<app_name>-static``."""
    paths = derive_paths(app_name)
    static_dir = paths["static_dir"]
    static_dir.mkdir(parents=True, exist_ok=True)
    mount_path = f"/{(prefix or app_name).strip('/')}-static"
    # Unmount first to allow idempotent re-runs in tests / hot reload.
    existing = [r for r in app.routes if getattr(r, "name", None) == f"{app_name}-static"]
    for route in existing:
        app.routes.remove(route)
    app.mount(mount_path, StaticFiles(directory=str(static_dir)), name=f"{app_name}-static")


def register_app_router(app: FastAPI, router: APIRouter) -> None:
    """Include a router if its prefix is not already registered."""
    prefixes = {getattr(r, "path", "") for r in app.routes}
    if router.prefix and router.prefix in prefixes:
        return
    app.include_router(router)


def _write_if_missing(path: Path, content: str) -> bool:
    """Write ``content`` only if the file does not already exist."""
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def create_app_template_files(
    app_name: str,
    *,
    prefix: str,
    title: str,
    db_filename: str | None = None,
    default_roles: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Create the generic boilerplate for a new SHIMS vertical app.

    Returns a summary of files created / skipped.  Domain-specific schema,
    services, routes, templates, and tests must be added next.
    """
    paths = ensure_app_package(app_name)
    db_filename = db_filename or f"{app_name}.sqlite3"
    prefix = "/" + prefix.strip("/")
    roles = default_roles or [
        {"username": "admin", "password": "admin123", "role": "admin"},
        {"username": "operator", "password": "operator123", "role": "operator"},
    ]

    # config.py
    config_py = paths["app_dir"] / "config.py"
    _write_if_missing(
        config_py,
        f'''"""App-specific configuration for {app_name}."""
from __future__ import annotations

import os
from pathlib import Path

from shared.config import ROOT_DIR, STORAGE_DIR

APP_DIR = ROOT_DIR / "apps" / "{app_name}"
STATIC_DIR = APP_DIR / "static"
TEMPLATES_DIR = APP_DIR / "templates"
DB_PATH = STORAGE_DIR / "{db_filename}"

DEFAULT_ROLES = {roles!r}

AI_MODEL = os.getenv("SHIMS_AI_MODEL", os.getenv("SHIMS_CODER_MODEL", "claude-sonnet-4-6"))
''',
    )

    # database.py
    db_py = paths["app_dir"] / "database.py"
    _write_if_missing(
        db_py,
        f'''"""SQLite layer for {app_name}."""
from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from .config import DB_PATH


@contextmanager
def get_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA journal_mode=WAL")
    con.execute("PRAGMA foreign_keys=ON")
    try:
        yield con
        con.commit()
    finally:
        con.close()


def ensure_schema() -> None:
    with get_db() as con:
        # TODO: add domain tables here
        con.execute("""
            CREATE TABLE IF NOT EXISTS app_meta (
                key TEXT PRIMARY KEY,
                value TEXT,
                updated_at REAL
            )
        """)
        con.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL,
                created_at REAL,
                updated_at REAL
            )
        """)


def query_one(sql: str, params: tuple[Any, ...] = ()) -> sqlite3.Row | None:
    with get_db() as con:
        return con.execute(sql, params).fetchone()


def query_all(sql: str, params: tuple[Any, ...] = ()) -> list[sqlite3.Row]:
    with get_db() as con:
        return con.execute(sql, params).fetchall()


def execute(sql: str, params: tuple[Any, ...] = ()) -> None:
    with get_db() as con:
        con.execute(sql, params)


def insert(sql: str, params: tuple[Any, ...] = ()) -> int:
    with get_db() as con:
        cur = con.execute(sql, params)
        return cur.lastrowid or 0
''',
    )

    # app.py skeleton
    app_py = paths["app_dir"] / "app.py"
    _write_if_missing(
        app_py,
        f'''"""FastAPI router factory for {title}."""
from __future__ import annotations

from fastapi import APIRouter, Request
from fastapi.templating import Jinja2Templates

from .config import APP_DIR, TEMPLATES_DIR
from .database import ensure_schema


def create_{app_name}_router() -> APIRouter:
    ensure_schema()
    router = APIRouter(prefix="{prefix}")
    templates = Jinja2Templates(directory=str(TEMPLATES_DIR))

    @router.get("")
    async def index(request: Request):
        return templates.TemplateResponse(request, "index.html", {{"request": request, "title": "{title}"}})

    # TODO: add domain routes in routers/ and include them here
    return router
''',
    )

    # templates/base.html
    base_html = paths["templates_dir"] / "base.html"
    _write_if_missing(
        base_html,
        f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{% block title %}}{title}{{% endblock %}}</title>
    <link rel="stylesheet" href="/{app_name}-static/css/{app_name}.css">
</head>
<body>
    {{% block content %}}{{% endblock %}}
    {{% block scripts %}}{{% endblock %}}
</body>
</html>
''',
    )

    # templates/index.html
    index_html = paths["templates_dir"] / "index.html"
    _write_if_missing(
        index_html,
        f'''{{% extends "base.html" %}}
{{% block title %}}{title}{{% endblock %}}
{{% block content %}}
<div class="container">
    <h1>{title}</h1>
    <p>Generated by SHIMS App Factory. Replace this with domain-specific UI.</p>
</div>
{{% endblock %}}
''',
    )

    # static/css/app_name.css
    css = paths["css_dir"] / f"{app_name}.css"
    _write_if_missing(
        css,
        f'''/* {title} styles */
body {{ font-family: system-ui, sans-serif; margin: 0; padding: 1rem; }}
.container {{ max-width: 1200px; margin: 0 auto; }}
''',
    )

    # static/js/app_name.js
    js = paths["js_dir"] / f"{app_name}.js"
    _write_if_missing(
        js,
        f'''// {title} frontend logic
console.log("{title} app loaded");
''',
    )

    # tests/test_app_name.py
    test_py = paths["tests_dir"] / f"test_{app_name}.py"
    _write_if_missing(
        test_py,
        f'''"""Tests for {title}."""
from __future__ import annotations

from fastapi.testclient import TestClient

from backend.app.main import app


def test_status():
    client = TestClient(app)
    res = client.get("{prefix}")
    assert res.status_code == 200
''',
    )

    created = [p.name for p in [config_py, db_py, app_py, base_html, index_html, css, js, test_py] if not _write_if_missing(p, "")]
    return {
        "ok": True,
        "app_name": app_name,
        "prefix": prefix,
        "paths": {k: str(v) for k, v in paths.items()},
        "files_created": created,
    }


def remove_app_package(app_name: str) -> dict[str, Any]:
    """Delete an app folder and its static mount (destructive; for sandbox/tests)."""
    paths = derive_paths(app_name)
    if paths["app_dir"].exists():
        shutil.rmtree(paths["app_dir"])
    return {"ok": True, "removed": str(paths["app_dir"])}
