"""
Evolution loop.

Two ways an improvement can be proposed:
  1. Mined from episodic memory ('every time the user asked about THF, the
     verifier flagged PXF_THF and the user thanked us — promote THF caution
     into the system prompt as a semantic concept').
  2. Generated by the smart brain reflecting on its own recent failures.

Either way, no candidate is auto-applied. Flow:
    proposed -> eval_passed/eval_failed -> (human) -> promoted/rolled_back
"""
from __future__ import annotations
import time
from typing import Iterable

from ..memory.types import EpisodicRecord, MemoryStore, SemanticConcept
from .archive import Archive, Candidate
from .harness import EvalCase, EvalReport, default_cases, run_harness


def propose_and_evaluate(
    archive: Archive,
    memory: MemoryStore | None = None,
    *,
    extra_cases: list[EvalCase] | None = None,
    proposer: "Proposer | None" = None,
) -> list[Candidate]:
    """One pass of the evolution loop. Returns the candidates created."""
    proposer = proposer or HeuristicProposer(memory)
    proposals = proposer.propose()

    cases = list(default_cases())
    if extra_cases:
        cases.extend(extra_cases)
    baseline = run_harness(cases)

    out: list[Candidate] = []
    for c in proposals:
        # Run the same harness; with prompt edits there's no behavior change
        # for the harness (it doesn't call the LLM), so we mainly check the
        # harness still passes — guards against accidental rule regressions.
        rep = run_harness(cases)
        c.scores = {
            "pass_rate": rep.pass_rate,
            "failed_critical": rep.failed_critical,
            "elapsed_s": rep.elapsed_s,
        }
        c.status = "eval_passed" if (rep.pass_rate >= baseline.pass_rate
                                       and rep.failed_critical == 0) else "eval_failed"
        archive.write(c)
        out.append(c)
    return out


def promote_candidate(archive: Archive, candidate_id: str) -> Candidate:
    """Mark a candidate promoted. Caller is responsible for actually applying it
    (writing the system prompt, loading the LoRA, etc.)."""
    c = archive.get(candidate_id)
    if c is None:
        raise KeyError(candidate_id)
    if c.status != "eval_passed":
        raise ValueError(f"cannot promote: status={c.status}")
    c.status = "promoted"
    c.promoted_at = time.time()
    archive.write(c)
    return c


def rollback_to(archive: Archive, candidate_id: str) -> Candidate:
    """Reverse: mark the current promoted candidate rolled back, promote `candidate_id`."""
    current = archive.current_promoted(kind=archive.get(candidate_id).kind  # type: ignore[union-attr]
                                        if archive.get(candidate_id) else "")
    if current is not None:
        current.status = "rolled_back"
        current.rolled_back_at = time.time()
        archive.write(current)
    c = archive.get(candidate_id)
    if c is None:
        raise KeyError(candidate_id)
    c.status = "promoted"
    c.promoted_at = time.time()
    c.rolled_back_at = None
    archive.write(c)
    return c


# ----- proposers ------------------------------------------------------------

class Proposer:
    def propose(self) -> list[Candidate]:
        raise NotImplementedError


class HeuristicProposer(Proposer):
    """Mine episodic memory for repeatable lessons; emit candidates."""

    def __init__(self, memory: MemoryStore | None) -> None:
        self.memory = memory

    def propose(self) -> list[Candidate]:
        out: list[Candidate] = []
        if self.memory is None:
            return out

        recent = self.memory.recent_episodes(limit=100)
        if not recent:
            return out

        # Lesson: frequently-hit hazard codes get promoted into system-prompt context.
        hazard_freq: dict[str, int] = {}
        for ep in recent:
            for tc in ep.tool_calls:
                if tc.get("tool") == "flag_hazards":
                    for iss in tc.get("issues", []):
                        hazard_freq[iss.get("code", "")] = hazard_freq.get(iss.get("code", ""), 0) + 1

        for code, n in sorted(hazard_freq.items(), key=lambda kv: -kv[1])[:3]:
            if not code or n < 3:
                continue
            payload = {
                "edit": "prepend_system_prompt",
                "text": f"Be especially careful when the user mentions structures matching {code}; "
                        f"this hazard has fired {n} times in recent interactions.",
                "lesson_source": "episodic_memory",
                "frequency": n,
            }
            out.append(Candidate.new(kind="prompt_edit", payload=payload,
                                      note=f"Recurring hazard {code} × {n}"))

        # Lesson: surface frequent semantic concepts to retrieve eagerly.
        # (No-op for now; placeholder for the SEAL-style self-edit hook.)
        return out
